---
title: "Curve_Analysis"
author: "Robin von Allmen"
date: "18 3 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
require(rgl)
options(rgl.useNULL = TRUE) # Suppress the separate window.
knitr::knit_hooks$set(webgl = hook_webgl)
library(geomorph)
#setwd("~/GitHub/Ichneumonidae/R-Scripts")
```

## Preparing Data


```{r cars, results=FALSE}
#setwd("~/GitHub/Ichneumonidae/R-Scripts")
landmark = readland.tps("Curve_Testfile.tps",specID = "ID", readcurves = T, warnmsg = TRUE)
landmark2 = readland.tps("Curve_Testfile.tps",specID = "ID", readcurves = F, warnmsg = TRUE)
##      define classifiers (subfam or tribes)
species = as.factor( substr( dimnames(landmark)[[3]], 1, 6))
subfam = as.factor( substr( dimnames(landmark)[[3]], 8, 13))
areolet = as.factor( substr( dimnames(landmark)[[3]], 15, 15))
tribe = as.factor( substr( dimnames(landmark)[[3]], 17, 19))


##      define Semilandmarks, first LM is the start, last one the end (those are both
##      fixed landmarks, in between are the semilandmarks):
sliders0 = define.sliders(c(10,22:29,11))
sliders1 = define.sliders(c(15,30:37,16))
sliders2 = define.sliders(c(13,38:45,4))
sliders3 = rbind(define.sliders(c(15,30:37,16)),define.sliders(c(10,22:29,11)))
sliders4 = rbind(define.sliders(c(13,38:45,4)),define.sliders(c(10,22:29,11)))
sliders5 = rbind(define.sliders(c(13,38:45,4)),define.sliders(c(15,30:37,16)))
sliders6 = rbind(define.sliders(c(13,38:45,4)),define.sliders(c(15,30:37,16)),define.sliders(c(10,22:29,11)))

##      procrustes fit - "superimposition" - rotates and scales the landmarks to their closest distance,
##      minimizing the shape and size difference:
proD0<-gpagen(landmark, surfaces = NULL, curves = sliders0,
             PrinAxes = FALSE, max.iter = NULL, ProcD = F, Proj = TRUE,
             print.progress = TRUE)

proD1<-gpagen(landmark, surfaces = NULL, curves = sliders1,
             PrinAxes = FALSE, max.iter = NULL, ProcD = F, Proj = TRUE,
             print.progress = TRUE)

proD2<-gpagen(landmark, surfaces = NULL, curves = sliders2,
             PrinAxes = FALSE, max.iter = NULL, ProcD = F, Proj = TRUE,
             print.progress = TRUE)

proD3<-gpagen(landmark, surfaces = NULL, curves = sliders3,
             PrinAxes = FALSE, max.iter = NULL, ProcD = F, Proj = TRUE,
             print.progress = TRUE)

proD4<-gpagen(landmark, surfaces = NULL, curves = sliders4,
             PrinAxes = FALSE, max.iter = NULL, ProcD = F, Proj = TRUE,
             print.progress = TRUE)

proD5<-gpagen(landmark, surfaces = NULL, curves = sliders5,
             PrinAxes = FALSE, max.iter = NULL, ProcD = F, Proj = TRUE,
             print.progress = TRUE)

proD6<-gpagen(landmark, surfaces = NULL, curves = sliders6,
             PrinAxes = FALSE, max.iter = NULL, ProcD = F, Proj = TRUE,
             print.progress = TRUE)

proD7<-gpagen(landmark2, surfaces = NULL,
             PrinAxes = FALSE, max.iter = NULL, ProcD = F, Proj = TRUE,
             print.progress = TRUE)
```

## PCA Analysis

```{r PCA, results=FALSE,echo=FALSE,fig.show= 'hide'}

PCA1 <-plotTangentSpace(proD0$coords, groups=tribe, legend=T)
PCA2 <-plotTangentSpace(proD1$coords, groups=tribe, legend=T)
PCA3 <-plotTangentSpace(proD2$coords, groups=tribe, legend=T)
PCA4 <-plotTangentSpace(proD3$coords, groups=tribe, legend=T)
PCA5 <-plotTangentSpace(proD4$coords, groups=tribe, legend=T)
PCA6 <-plotTangentSpace(proD5$coords, groups=tribe, legend=T)
PCA7 <-plotTangentSpace(proD6$coords, groups=tribe, legend=T)
```
```{r PLOT WITHOUT CURVES}

PCA0 <-plotTangentSpace(proD7$coords, groups=tribe, legend=T)
title(main="Without Curve")
```


```{r PLOT CURVES, fig.show="80%", fig.height= 10, fig.width= 10}

par(mfrow= c(4,2))
plot(PCA1$pc.scores[,1],PCA1$pc.scores[,2], col=tribe, asp=T, las=1,pch=16, cex=1.3, main= "1M+CU")
legend("topright", legend= levels(tribe), col=palette(), pch=rep(19,14) )

plot(PCA2$pc.scores[,1],PCA2$pc.scores[,2], col=tribe, asp=T, las=1,pch=16, cex=1.3, main= "2m-cu")

plot(PCA3$pc.scores[,1],PCA3$pc.scores[,2], col=tribe, asp=T, las=1,pch=16, cex=1.3, main = "RS")
plot(PCA4$pc.scores[,1],PCA4$pc.scores[,2], col=tribe, asp=T, las=1,pch=16, cex=1.3, main = "1M+Cu & 2m-cu")
plot(PCA5$pc.scores[,1],PCA5$pc.scores[,2], col=tribe, asp=T, las=1,pch=16, cex=1.3, main= "1M+Cu & RS")
plot(PCA6$pc.scores[,1],PCA6$pc.scores[,2], col=tribe, asp=T, las=1,pch=16, cex=1.3, main= "2m-Cu & RS")
plot(PCA7$pc.scores[,1],PCA7$pc.scores[,2], col=tribe, asp=T, las=1,pch=16, cex=1.3, main= "1M+Cu & 2m-cu & RS")

```
